package(default_visibility = ["//visibility:public"])

java_library(
    name = "testing",
    testonly = True,
    srcs = glob(["*.java"]),
    deps = [
        "//src/java/com/github/curiousleo/cqengine/phtree/common",
        "//thirdparty:cqengine",
    ],
)
