dist: trusty
sudo: required
jdk:
  - openjdk8
before_install:
  - curl --location 'https://github.com/bazelbuild/bazel/releases/download/0.18.0/bazel-0.18.0-installer-linux-x86_64.sh' | sudo bash
script:
  - bash tools/check-bazel.sh
  - bash tools/check-java.sh
  - bazel build //...
  - bazel test //...

