package(default_visibility = ["//visibility:public"])

java_library(
    name = "query",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/github/curiousleo/cqengine/phtree/common",
        "//thirdparty:cqengine",
        "//thirdparty:phtree",
    ],
)
