package(default_visibility = ["//visibility:public"])

java_test(
    name = "index",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/github/curiousleo/cqengine/phtree/common",
        "//java/com/github/curiousleo/cqengine/phtree/index",
        "//java/com/github/curiousleo/cqengine/phtree/query",
        "//javatests/com/github/curiousleo/cqengine/phtree/testing",
        "//thirdparty:concurrent_trees",
        "//thirdparty:cqengine",
        "//thirdparty:phtree",
        "//thirdparty:testing",
    ],
)
