package(default_visibility = ["//visibility:private"])

java_test(
    name = "attribute",
    srcs = glob(["*.java"]),
    deps = [
        "//src/java/com/github/curiousleo/cqengine/phtree/attribute",
        "//src/java/com/github/curiousleo/cqengine/phtree/common",
        "//thirdparty:cqengine",
        "//thirdparty:phtree",
        "//thirdparty:testing",
    ],
)
