name: CI
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    env:
      BAZEL_VERSION: 4.1.0
    steps:

    - name: Install Bazel
      run: |
        BAZEL_DEB="bazel_${BAZEL_VERSION}-linux-x86_64.deb"
        curl -sSL -o "${BAZEL_DEB}" "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/${BAZEL_DEB}"
        sudo dpkg -i "${BAZEL_DEB}"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Check formatting
      run: |
        ./tools/check-bazel
        ./tools/check-java

    - run: bazel build //...

    - run: bazel test //...
