name: CI
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    env:
      BAZEL_VERSION: 3.4.1
    steps:

    - name: Install Bazel
      run: |
        BAZEL_DEB='bazel_3.4.1-linux-x86_64.deb'
        curl -sSL -o "${BAZEL_DEB}" "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/${BAZEL_DEB}"
        sudo dpkg -i "${BAZEL_DEB}"

    - name: Check formatting
      run: |
        bash tools/check-bazel
        bash tools/check-java

    - run: bazel build //...

    - run: bazel test //...
